// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReadyToGoTravel.Retention.Persistence;

#nullable disable

namespace ReadyToGoTravel.Retention.Persistence.Migrations
{
    [DbContext(typeof(RetentionDbContext))]
    partial class RetentionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("retention")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReadyToGoTravel.Retention.Domain.LegalHold", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorizedOwnerSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("authorized_owner_subject");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("MatterReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("matter_reference");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("ReleaseReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("release_reason");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at_utc");

                    b.Property<string>("ReleasedBySubject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("released_by_subject");

                    b.Property<DateTimeOffset>("ReviewByUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_by_utc");

                    b.HasKey("Id");

                    b.HasIndex("ReleasedAtUtc");

                    b.ToTable("legal_holds", "retention");
                });

            modelBuilder.Entity("ReadyToGoTravel.Retention.Domain.LegalHoldAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorSubject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_subject");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("LegalHoldId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_hold_id");

                    b.HasKey("Id");

                    b.HasIndex("LegalHoldId");

                    b.ToTable("legal_hold_audit_events", "retention");
                });

            modelBuilder.Entity("ReadyToGoTravel.Retention.Domain.LegalHoldScope", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ComponentBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_booking_id");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("LegalHoldId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_hold_id");

                    b.Property<string>("RecordClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("record_class");

                    b.Property<Guid?>("SupportTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("support_ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("LegalHoldId");

                    b.HasIndex("RecordClass", "ComponentBookingId");

                    b.HasIndex("RecordClass", "CustomerId");

                    b.HasIndex("RecordClass", "SupportTicketId");

                    b.ToTable("legal_hold_scopes", "retention", t =>
                        {
                            t.HasCheckConstraint("ck_legal_hold_scopes_exactly_one_subject", "(CASE WHEN customer_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN component_booking_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN support_ticket_id IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("ReadyToGoTravel.Retention.Domain.RetentionDeletionReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("failure_count");

                    b.Property<string>("FailureSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_summary");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("policy_version");

                    b.Property<string>("RecordClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("record_class");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("success_count");

                    b.HasKey("Id");

                    b.HasIndex("RecordClass", "CompletedAtUtc");

                    b.ToTable("retention_deletion_receipts", "retention");
                });

            modelBuilder.Entity("ReadyToGoTravel.Retention.Domain.RetentionOperationalCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<string>("RecordClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("record_class");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("scope");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique();

                    b.ToTable("retention_operational_cases", "retention");
                });

            modelBuilder.Entity("ReadyToGoTravel.Retention.Domain.LegalHoldAuditEvent", b =>
                {
                    b.HasOne("ReadyToGoTravel.Retention.Domain.LegalHold", null)
                        .WithMany()
                        .HasForeignKey("LegalHoldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Retention.Domain.LegalHoldScope", b =>
                {
                    b.HasOne("ReadyToGoTravel.Retention.Domain.LegalHold", null)
                        .WithMany("Scopes")
                        .HasForeignKey("LegalHoldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Retention.Domain.LegalHold", b =>
                {
                    b.Navigation("Scopes");
                });
#pragma warning restore 612, 618
        }
    }
}
