// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReadyToGoTravel.Booking.Persistence;

#nullable disable

namespace ReadyToGoTravel.Booking.Persistence.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260808010000_Slice5BookingReconciliation")]
    partial class Slice5BookingReconciliation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("booking")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReadyToGoTravel.Booking.Bookings.ComponentBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentCanonicalHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_canonical_hash");

                    b.Property<int>("CurrentVersionNumber")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("current_version_number");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("failure_code");

                    b.Property<DateTimeOffset?>("LastReconciledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reconciled_at");

                    b.Property<DateTimeOffset?>("NextDepartureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_departure_at");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("offer_id");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("product");

                    b.Property<string>("ProviderBinding")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider_binding");

                    b.Property<string>("ProviderBookingReference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_booking_reference");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("checkout_session_id")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("ProviderBookingReference")
                        .IsUnique()
                        .HasFilter("provider_booking_reference IS NOT NULL");

                    b.HasIndex("checkout_session_id");

                    b.ToTable("component_bookings", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.BookingRecoveryCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ComponentBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("reason");

                    b.Property<Guid>("checkout_session_id")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("checkout_session_id", "DedupeKey", "Reason")
                        .IsUnique()
                        .HasDatabaseName("ux_booking_recovery_cases_checkout_dedupe_reason");

                    b.ToTable("booking_recovery_cases", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("TermsHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("terms_hash");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<string>("TransactionCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("transaction_currency");

                    b.Property<Guid>("checkout_session_id")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("checkout_session_id", "Number")
                        .IsUnique();

                    b.ToTable("checkout_revisions", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutRevisionComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<decimal>("MinimumTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("minimum_total");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("offer_id");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("product");

                    b.Property<string>("ProductDetail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("product_detail");

                    b.Property<string>("ProviderBinding")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider_binding");

                    b.Property<string>("ProviderRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider_revision");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("TermsHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("terms_hash");

                    b.Property<Guid>("checkout_revision_id")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_revision_id");

                    b.HasKey("Id");

                    b.HasIndex("checkout_revision_id");

                    b.ToTable("checkout_revision_components", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerLocale")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("customer_locale");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("NotificationTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("notification_time_zone_id");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TripId");

                    b.ToTable("checkout_sessions", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.TravellerSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AgeAtTravel")
                        .HasColumnType("integer")
                        .HasColumnName("age_at_travel");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("given_name");

                    b.Property<DateTimeOffset?>("GuardianAuthorityConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guardian_authority_confirmed_at");

                    b.Property<bool>("IsMinor")
                        .HasColumnType("boolean")
                        .HasColumnName("is_minor");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("offer_id");

                    b.Property<Guid>("TravellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveller_id");

                    b.Property<Guid>("checkout_session_id")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("checkout_session_id", "OfferId", "TravellerId")
                        .IsUnique();

                    b.ToTable("traveller_snapshots", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operation");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "Operation", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_records_customer_operation_key");

                    b.ToTable("idempotency_records", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Notifications.NotificationOutboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid>("BookingVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_version_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<Guid>("CheckoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_id");

                    b.Property<Guid>("ComponentBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("DeliveryReference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("delivery_reference");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("error_code");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("lease_owner");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("locale");

                    b.Property<DateTime>("NotBeforeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("template");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BookingVersionId");

                    b.HasIndex("DedupeKey")
                        .IsUnique();

                    b.HasIndex("Status", "NotBeforeUtc");

                    b.ToTable("notification_outbox", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Payments.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("failure_code");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderPaymentReference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_payment_reference");

                    b.Property<string>("ProviderReturnReference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_return_reference");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("checkout_session_id")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("ProviderReturnReference")
                        .IsUnique()
                        .HasFilter("provider_return_reference IS NOT NULL");

                    b.HasIndex("checkout_session_id");

                    b.ToTable("payment_attempts", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Reconciliation.BookingVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("canonical_hash");

                    b.Property<string>("CanonicalSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_snapshot_json");

                    b.Property<string>("CanonicalisationVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("canonicalisation_version");

                    b.Property<Guid>("ComponentBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_booking_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DiffJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diff_json");

                    b.Property<DateTimeOffset?>("EffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at");

                    b.Property<string>("FlagsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flags_json");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metadata_json");

                    b.Property<DateTimeOffset?>("NextDepartureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_departure_at");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("ComponentBookingId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("booking_versions", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Reconciliation.OperationalCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<Guid?>("ComponentBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique();

                    b.ToTable("operational_cases", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Reconciliation.ReconciliationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ComponentBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_booking_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("error_code");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("reconciliation_attempts", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Reconciliation.ReconciliationWork", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<Guid>("ComponentBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_booking_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("last_error_code");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("lease_owner");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("product");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ComponentBookingId")
                        .IsUnique();

                    b.HasIndex("Product", "Status", "DueAtUtc");

                    b.ToTable("reconciliation_work", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Webhooks.WebhookInboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("error_code");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("event_name");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<string>("RawBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_body");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<bool>("Sandbox")
                        .HasColumnType("boolean")
                        .HasColumnName("sandbox");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.HasIndex("Provider", "Environment", "EventId")
                        .IsUnique();

                    b.ToTable("webhook_inbox", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Bookings.ComponentBooking", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Checkout.CheckoutSession", null)
                        .WithMany("Components")
                        .HasForeignKey("checkout_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.BookingRecoveryCase", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Checkout.CheckoutSession", null)
                        .WithMany("RecoveryCases")
                        .HasForeignKey("checkout_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutRevision", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Checkout.CheckoutSession", null)
                        .WithMany("Revisions")
                        .HasForeignKey("checkout_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutRevisionComponent", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Checkout.CheckoutRevision", null)
                        .WithMany("Components")
                        .HasForeignKey("checkout_revision_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutSession", b =>
                {
                    b.OwnsOne("ReadyToGoTravel.Booking.Checkout.CheckoutAcceptance", "AcceptedRevision", b1 =>
                        {
                            b1.Property<Guid>("checkout_session_id")
                                .HasColumnType("uuid")
                                .HasColumnName("checkout_session_id");

                            b1.Property<DateTimeOffset>("AcceptedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("accepted_at");

                            b1.Property<decimal>("AcceptedTotal")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("accepted_total");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<string>("PolicyVersion")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("policy_version");

                            b1.Property<int>("RevisionNumber")
                                .HasColumnType("integer")
                                .HasColumnName("revision_number");

                            b1.Property<string>("TermsHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("terms_hash");

                            b1.HasKey("checkout_session_id");

                            b1.ToTable("checkout_acceptances", "booking");

                            b1.WithOwner()
                                .HasForeignKey("checkout_session_id");
                        });

                    b.OwnsOne("ReadyToGoTravel.Booking.Payments.PaymentPlan", "PaymentPlan", b1 =>
                        {
                            b1.Property<Guid>("checkout_session_id")
                                .HasColumnType("uuid")
                                .HasColumnName("checkout_session_id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<string>("CustomerPaymentRoute")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("customer_payment_route");

                            b1.Property<string>("MerchantModel")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("merchant_model");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("provider");

                            b1.Property<string>("RefundOwner")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("refund_owner");

                            b1.Property<string>("RequiredCustomerAction")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("required_customer_action");

                            b1.Property<bool>("SeparateComponentCharges")
                                .HasColumnType("boolean")
                                .HasColumnName("separate_component_charges");

                            b1.Property<string>("SettlementRoute")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("settlement_route");

                            b1.HasKey("checkout_session_id");

                            b1.ToTable("payment_plans", "booking");

                            b1.WithOwner()
                                .HasForeignKey("checkout_session_id");
                        });

                    b.Navigation("AcceptedRevision");

                    b.Navigation("PaymentPlan");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.TravellerSnapshot", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Checkout.CheckoutSession", null)
                        .WithMany("TravellerSnapshots")
                        .HasForeignKey("checkout_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Notifications.NotificationOutboxItem", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Reconciliation.BookingVersion", null)
                        .WithMany()
                        .HasForeignKey("BookingVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Payments.PaymentAttempt", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Checkout.CheckoutSession", null)
                        .WithMany("PaymentAttempts")
                        .HasForeignKey("checkout_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Reconciliation.BookingVersion", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Bookings.ComponentBooking", null)
                        .WithMany()
                        .HasForeignKey("ComponentBookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Reconciliation.ReconciliationAttempt", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Reconciliation.ReconciliationWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Reconciliation.ReconciliationWork", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Bookings.ComponentBooking", null)
                        .WithMany()
                        .HasForeignKey("ComponentBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutRevision", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutSession", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("PaymentAttempts");

                    b.Navigation("RecoveryCases");

                    b.Navigation("Revisions");

                    b.Navigation("TravellerSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
