// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReadyToGoTravel.Booking.Persistence;

#nullable disable

namespace ReadyToGoTravel.Booking.Persistence.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("booking")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReadyToGoTravel.Booking.Bookings.ComponentBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("failure_code");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("offer_id");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("product");

                    b.Property<string>("ProviderBinding")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider_binding");

                    b.Property<string>("ProviderBookingReference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_booking_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("checkout_session_id")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("ProviderBookingReference")
                        .IsUnique()
                        .HasFilter("provider_booking_reference IS NOT NULL");

                    b.HasIndex("checkout_session_id");

                    b.ToTable("component_bookings", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.BookingRecoveryCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ComponentBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("reason");

                    b.Property<Guid>("checkout_session_id")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("checkout_session_id", "DedupeKey", "Reason")
                        .IsUnique()
                        .HasDatabaseName("ux_booking_recovery_cases_checkout_dedupe_reason");

                    b.ToTable("booking_recovery_cases", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("TermsHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("terms_hash");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<string>("TransactionCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("transaction_currency");

                    b.Property<Guid>("checkout_session_id")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("checkout_session_id", "Number")
                        .IsUnique();

                    b.ToTable("checkout_revisions", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutRevisionComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<decimal>("MinimumTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("minimum_total");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("offer_id");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("product");

                    b.Property<string>("ProductDetail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("product_detail");

                    b.Property<string>("ProviderBinding")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider_binding");

                    b.Property<string>("ProviderRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider_revision");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("TermsHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("terms_hash");

                    b.Property<Guid>("checkout_revision_id")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_revision_id");

                    b.HasKey("Id");

                    b.HasIndex("checkout_revision_id");

                    b.ToTable("checkout_revision_components", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TripId");

                    b.ToTable("checkout_sessions", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.TravellerSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AgeAtTravel")
                        .HasColumnType("integer")
                        .HasColumnName("age_at_travel");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("given_name");

                    b.Property<DateTimeOffset?>("GuardianAuthorityConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guardian_authority_confirmed_at");

                    b.Property<bool>("IsMinor")
                        .HasColumnType("boolean")
                        .HasColumnName("is_minor");

                    b.Property<Guid>("TravellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveller_id");

                    b.Property<Guid>("checkout_session_id")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("checkout_session_id", "TravellerId")
                        .IsUnique();

                    b.ToTable("traveller_snapshots", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operation");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "Operation", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_records_customer_operation_key");

                    b.ToTable("idempotency_records", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Payments.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("failure_code");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderPaymentReference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_payment_reference");

                    b.Property<string>("ProviderReturnReference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_return_reference");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("checkout_session_id")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("ProviderReturnReference")
                        .IsUnique()
                        .HasFilter("provider_return_reference IS NOT NULL");

                    b.HasIndex("checkout_session_id");

                    b.ToTable("payment_attempts", "booking");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Bookings.ComponentBooking", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Checkout.CheckoutSession", null)
                        .WithMany("Components")
                        .HasForeignKey("checkout_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.BookingRecoveryCase", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Checkout.CheckoutSession", null)
                        .WithMany("RecoveryCases")
                        .HasForeignKey("checkout_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutRevision", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Checkout.CheckoutSession", null)
                        .WithMany("Revisions")
                        .HasForeignKey("checkout_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutRevisionComponent", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Checkout.CheckoutRevision", null)
                        .WithMany("Components")
                        .HasForeignKey("checkout_revision_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutSession", b =>
                {
                    b.OwnsOne("ReadyToGoTravel.Booking.Checkout.CheckoutAcceptance", "AcceptedRevision", b1 =>
                        {
                            b1.Property<Guid>("checkout_session_id")
                                .HasColumnType("uuid")
                                .HasColumnName("checkout_session_id");

                            b1.Property<DateTimeOffset>("AcceptedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("accepted_at");

                            b1.Property<decimal>("AcceptedTotal")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("accepted_total");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<string>("PolicyVersion")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("policy_version");

                            b1.Property<int>("RevisionNumber")
                                .HasColumnType("integer")
                                .HasColumnName("revision_number");

                            b1.Property<string>("TermsHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("terms_hash");

                            b1.HasKey("checkout_session_id");

                            b1.ToTable("checkout_acceptances", "booking");

                            b1.WithOwner()
                                .HasForeignKey("checkout_session_id");
                        });

                    b.Navigation("AcceptedRevision");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.TravellerSnapshot", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Checkout.CheckoutSession", null)
                        .WithMany("TravellerSnapshots")
                        .HasForeignKey("checkout_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Payments.PaymentAttempt", b =>
                {
                    b.HasOne("ReadyToGoTravel.Booking.Checkout.CheckoutSession", null)
                        .WithMany("PaymentAttempts")
                        .HasForeignKey("checkout_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutRevision", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("ReadyToGoTravel.Booking.Checkout.CheckoutSession", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("PaymentAttempts");

                    b.Navigation("RecoveryCases");

                    b.Navigation("Revisions");

                    b.Navigation("TravellerSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
